#!/usr/bin/env python3
#
# Copyright (C) 2021 VyOS maintainers and contributors
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 or later as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
import sys

from vyos.template import is_ipv4

if __name__ == '__main__':

    if len(sys.argv) != 2:
        sys.exit(1)

    value = sys.argv[1].split(':')

    # entries with less than three blocks must be valid regex
    if not len(value) == 3:
        try:
            re.compile(sys.argv[1])
            sys.exit(0)
        except re.error:
            sys.exit(1)
    # otherwise if all three blocks are digits, it is an exact match
    elif (is_ipv4(value[0]) or value[0].isdigit()) \
        and value[1].isdigit() \
        and value[2].isdigit():
        sys.exit(0)
    # else, it has to be a valid regex.
    else:
        try:
            re.compile(sys.argv[1])
            sys.exit(0)
        except re.error:
            sys.exit(1)

    # default exit 1; should never be reached
    sys.exit(0)
