name: Check for unused imports using Pylint
on:
  pull_request:
    branches:
      - current
      - equuleus
      - sagitta
      - circinus
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check-unused-imports:
    uses: vyos/.github/.github/workflows/check-unused-imports.yml@current
    secrets: inherit
